[project]
name = "automate-guardian"
authors = ["Blockchain Financial Solutions Team"]
description = "Decentralized bond management platform on Stacks blockchain"
telemetry = false
requirements = []
[contracts.bond-guardian]
path = "contracts/bond-guardian.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
